@Concept.PatientRecordSystem_HostAddress = http://localhost:5025

POST {{Concept.PatientRecordSystem_HostAddress}}/patient/
Content-Type: application/json

{
  "resourceType": "Patient",  
  "identifier": [
    {
      "system": "http://example.com/identifiers/mrn",
      "value": "553456"
    }
  ],
  "name": [
    {
      "use": "official",
        "family": "Poe",
      "given": [
        "Edgar",
        "Allan"
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "219-555-1234",
      "use": "home"
    },
    {
      "system": "email",
      "value": "edgar.poe@example.com",
      "use": "home"
    }
  ],
 "communication": [
    {
      "language": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/us/core/ValueSet/simple-language",
            "code": "en",
            "display": "English"
          }
        ],
        "text": "English"
      },
      "preferred": true
    }
  ],
  "gender": "male",
  "birthDate": "1972-05-12",
  "address": [
    {
      "use": "home",
      "line": [
        "123 Main Street"
      ],
      "city": "New York",
      "state": "NY",
      "postalCode": "10001",
      "country": "USA"
    }
  ],
  "generalPractitioner": [
    {
      "reference": "Practitioner/41f8b542-9879-4f4f-8a6f-071c938fd3ef"
    }
  ]
}


###
POST {{Concept.PatientRecordSystem_HostAddress}}/practitioner/
Content-Type: application/json

{
  "resourceType": "Practitioner",
  "identifier": [
    {
      "system": "http://hl7.org/fhir/sid/us-npi",
      "value": "1942902853"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "House",
      "given": [
        "Gregory"
      ],
      "prefix": [
        "Dr."
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "666-5858",
      "use": "work"
    },
    {
      "system": "email",
      "value": "greg.house@example.com",
      "use": "work"
    }
  ]
}

